name: verify project

on: [push, pull_request]

jobs:
  install:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-lock-${{ hashFiles('**/composer.lock') }}

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Cache phive packages
      id: phive-tools-cache
      uses: actions/cache@v3
      with:
        path: tools
        key: phive-tools-${{ hashFiles('**/.phive/phars.xml') }}

    - name: Install phive tools
      if: steps.phive-tools-cache.outputs.cache-hit != 'true'
      run: wget -O phive https://phar.io/releases/phive.phar && chmod +x phive && ./phive install --trust-gpg-keys 4AA394086372C20A,12CE0F1D262429A5,5E6DDE998AB73B8E,8AC0BAA79732DD42,C5095986493B4AA0 && chmod -R +x ./tools/

    - name: 'Tar project'
      run: tar -cf project.tar .

    - uses: actions/upload-artifact@v3
      with:
        name: installed-project
        path: project.tar

  phplint:
    needs: install
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: installed-project

    - name: Untar project.
      run:  tar -xf project.tar

    - name: Run php lint
      run: find ./src/ ./tests/ -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

  phpcs:
    needs: phplint
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: installed-project

    - name: Untar project.
      run:  tar -xf project.tar

    - name: Run phpcs
      run: ./tools/phpcs --standard=PSR12 --extensions=php ./src/ ./tests/

  test:
    needs: phplint
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: installed-project

    - name: Untar project.
      run:  tar -xf project.tar

    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug

    - name: Run PHPUnit test
      run: ./tools/phpunit -c ./ci/phpunit.xml

  static-analysis:
    needs: phplint
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: installed-project

    - name: Untar project.
      run:  tar -xf project.tar

    - name: Run Psalm
      run: ./tools/psalm -c ./ci/psalm.xml --shepherd --no-cache
